# Generated by Django 3.0 on 2019-12-15 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=1024, verbose_name='Name of the College')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('achievemennts', models.TextField(max_length=1024, verbose_name='Personal Achievements')),
                ('profile', models.TextField(max_length=1024, verbose_name='Preferred Job Profile')),
                ('cgpa', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='CGPA (0.00 - 10.00)')),
                ('branch', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
